### ISSUE TITLE
cpuaffinity.py error

### ISSUE THREAD

**Issue by pepebc** [wolfc01/procexp#13]
I have tried to apply affinity to CPU, but I get this error:
Unhandled exception:
IndexError '>: list index out of range on line 16, file cpuaffinity.py

**Comment by plonibarploni** [comment]
This project doesn't seem to be maintained. You might want to have a look at https://github.com/ftso/psymon, which looks like it might be revived now, although I can't get it to run :(

**Comment by pepebc** [comment]
> This project doesn't seem to be maintained. You might want to have a look at https://github.com/ftso/psymon, which looks like it might be revived now, although I can't get it to run, or [qps](https://github.com/lxqt/qps), although that too has [issues](https://github.com/lxqt/qps/issues/101) :(

OK, thanks
