### ISSUE TITLE
update deps and build instructions

### ISSUE THREAD

**Issue by gregpalaci** [wolfc01/procexp#16]
I'm on Ubuntu 20.04, seems like python-qwt5-qt4  doesn't exist anymore. 
Not a python expert but I get this when trying to run
```
./procexp.py                 
Traceback (most recent call last):
  File "./procexp.py", line 30, in <module>
    import procreader.reader
  File "/home/gnb/Downloads/procexp-master/procreader/reader.py", line 25, in <module>
    import singleprocess
  File "/home/gnb/Downloads/procexp-master/singleprocess.py", line 23, in <module>
    from PyQt5 import Qwt
ImportError: cannot import name 'Qwt' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)

```

```
❯ python3
Python 3.8.5 (default, Jul 22 2020, 18:54:26) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import Qwt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Qwt' from 'PyQt5' (/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5/lib/python3.8/site-packages/PyQt5/__init__.py)
>>> from PyQt5 import QtCore, QtGui, QtWidgets
>>> 
```

**Comment by MiraSoulGlo** [comment]
I'm about as hardcore of "not an expert" as it can probably get as far as the "people contributing to an Issues the

**Comment by Pound-Hash** [comment]
Debian 11 is missing the packages: **python-qwt5-qt4** & **python-configobj**

**Comment by gregpalaci** [comment]
https://github.com/wolfc01/procexp/issues/16#issuecomment-817025348
ah apologies, I only meant last year to let the authors know the instructions werent clear didn't include what was necessary to get started... from the Get Stared. I'm glad zip works, that could replace the get started section as solution I guess?

I haven't tested it's been over a year but seems this might be relevant also https://github.com/wolfc01/procexp/issues/16#issuecomment-965727557

closing out of indifference.
