### ISSUE TITLE
Don't start on Arclinux

### ISSUE THREAD

**Issue by smopro** [wolfc01/procexp#17]
```
./procexp.py 
Traceback (most recent call last):
  File "./procexp.py", line 30, in <module>
    import procreader.reader
  File "/home/smopro/procexp/procreader/reader.py", line 25, in <module>
    import singleprocess
  File "/home/smopro/procexp/singleprocess.py", line 23, in <module>
    from PyQt5 import Qwt
ImportError: cannot import name 'Qwt' from 'PyQt5' (/usr/lib/python3.8/site-packages/PyQt5/__init__.py)
```
Linux test-arch 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux

**Comment by TheOneWhoseUsernameWasTaken** [comment]
I had that issue under Linux Mint 20.1. I managed to solve it by installing the package "python3-pyqt5.qwt", along with its dependencies.

I don't know what the package is called under Arch, but you probably just need to install the correct one. The instructions in the README.md seem to be a bit outdated and are still for older distributions.

Try and figure out which package gives you the Python version of the Qwt6 technical widget library, and then install that.

**Comment by cmorgenstern** [comment]
Should be fixed for the latest [AUR version](https://aur.archlinux.org/packages/procexp/) on Arch Linux - uses [python-pyqt-qwt](https://aur.archlinux.org/packages/python-pyqt-qwt/) to satisfy the missing `Qwt` dependency.
